version: '3.4'

services:
  mongodb:
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  hipermicroservice:
    container_name: hipermicroservice
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - DataBaseSettings__ConnectionString=mongodb://mongodb:27017
    depends_on:
     - mongodb 
    ports:
     - "8000:80"
